### PR TITLE
Add IntersectionObserver helpers

### PR DESCRIPTION
**Pull request by andrewrubin**
Thought we could get some use out of this. Two helpers: one for making an IntersectionObserver, and one for attaching it to a group of elements. You can get the same effect with the WTC Viewport controller, but this is much more stripped-back, which could be useful. Example usage below. Let me know your thoughts! 

```js
const loadImage = (element) => {
  element.src = element.dataset.src;
  element.addEventListener('load', () => {
    element.classList.add('loaded');
  });
}

const images = document.querySelectorAll('img');


// Usage
// ==================

// you don't actually have to pass anything to this,
// but you're free to provide intersect/leave callbacks,
// config object, and an "unobserve" (once) boolean.
const myObserver = utilities.createIntersectionObserver({
  config: {
    rootMargin: '0px 0px 400px 0px'
  },
  once: true,
  onIntersect: loadImage
});

utilities.attachIntersectionObserver(myObserver, images)
```

### CODE REVIEW

**Comment by andrewrubin** [comment]
Example in action: https://codepen.io/andyranged/pen/2ac27f4161638f6353cb2f99c044cc1f?editors=0010

**Comment by liamegan** [comment]
The only issue I see here is that in an effort to abstract away the verbosity of the IO boilerplate, it also abstracts away some of the more advanced functionality. I'm happy for dissenting opinions here @marlonmarcello and @NicholasLancey, but I don't know that we gain much with this addition to the utilities.

**Comment by marlonmarcello** [comment]
I like this idea very much @andrewrubin and I think we can make a `lazy-load` class with a more robust API instead, what do you think?
Thanks for bring this idea with examples and all. Really nice initiative.

**Comment by andrewrubin** [comment]
Thanks for your input, guys. @liamegan yeah, fair enough—I can see how the use cases for something this abstract might be few and far between. @marlonmarcello thanks for the kind words—I'll put something together as a proposal for a new lazy load class, and we'll take it from there.

**Pull request closed without merging**
