### PR TITLE
Adding async image load utility

### PR DESCRIPTION
**Pull request by liamegan**
Pretty simple function that generates a promise given an image object and an SRC.

There are some pretty big changes that this generated in the documentation and I'm not entirely sure why.

### CODE REVIEW

**Comment by marlonmarcello** [comment]
@liamegan what do you think of making this function return the image?
So instead of:
```js
const img = new Image();
img.crossOrigin = "anonymous";
const p = asyncImageLoad(img, '/assets/images/cool_image.png')
p.then((img) => {
  console.log('image loaded!')
}, (reason) => {
  console.log('image didn\'t load')
});
```

We would do:
```js
const img = asyncImageLoad({ img: "/assets/images/cool_image.png", crossOrigin: "anonymous" }).then(img => //img loaded);

// with async/await
const img = await asyncImageLoad({src: "/assets/images/cool_image.png", crossOrigin: "anonymous" })
// img loaded
```

And the function itself could change to something like:
```js
export const asyncImageLoad = function(props) {
  return new Promise((resolve, reject) => {
    const img = new Image;
    img.onload = () => resolve(img);
    img.onerror = reject;

    for(let [key, val] of Object.entries(props) {
      img[key] = value;
    }
  })
} 
```
That would even allow for the use of `srcset`

**Comment by marlonmarcello** [comment]
Tested that on console and it worked.
Also, if we are concerned and we wanna have `src` added for last on the image we can use spread operators:
```js
export const asyncImageLoad = function({src, ...props) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    for(let [key, val] of Object.entries(props)) {
      img[key] = val;
    }
    img.src = src;    
  })
} 
```

**Comment by liamegan** [comment]
The problem with this approach is twofold:
1. It doesn't let you do some sometimes necessary things before loading the
image - like adding crossorigin; and
2. it assumes you always create the image with javascript (not always the
case).

---------------------------------------------------------------
Liam Egan  |  We The Collective Design Inc.

37 Dunlevy Ave.
Vancouver BC V6A 3A3

Phone: +1 (604) 363-6466

www.wethecollective.com

**Comment by liamegan** [comment]
Deleted my comment, this is good. Will be interesting to see if we run into use cases where we need to pull the image element from elsewehere. I'm good with your changes.

**Review by marlonmarcello — APPROVED** [review]

**Pull request merged**
