### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by liamegan**
Hi guys can you please take a look through this and let me know what you think. You can see my list of items here:
https://wethecollective.teamwork.com/#tasks/12082473

### CODE REVIEW

**Comment by liamegan** [comment]
> All looks great @liamegan. Thanks for the thorough documentation as well. I think one thing we could benefit from is a method that directly equates to `.closest()`. It could even just be the [polyfill](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill) we currently use. Comes in handy when checking parent nodes, on a click listener for example… Thoughts?

There's a question about this on TW, see:
https://wethecollective.teamwork.com/#tasks/12082493

Essentially what I want to find out is whether we can selectively polyfill this with Babel, arguably this is one of the use-cases of the library.

@marlonmarcello any insight here?

**Comment by marlonmarcello** [comment]
Not really @liamegan we either have to import an npm package with a polyfill or add ourselves. I always use the polyfill on MDN.
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill

We don't support IE11 anymore and hopefully the pokes will soon follow that same standard, I don't think we need to add this.

**Comment by marlonmarcello** [comment]
Good to merge!

**Comment by liamegan** [comment]
Ok great. Unless anyone has any major objections I'm going to leave the
closest polyfill out.

**Pull request merged**
